Fix GLSL compilation error: implicit cast of vec3 to vec4.
Using .xyzx is fine here since the last component is never used.
Also, storage is already allocated…